// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR8hmptTHEnnjryLALNkoK-EJlCUBu2T4',
    appId: '1:82035476438:web:78ff34ecfc74e4b0eec677',
    messagingSenderId: '82035476438',
    projectId: 'leadapp-890b6',
    authDomain: 'leadapp-890b6.firebaseapp.com',
    storageBucket: 'leadapp-890b6.firebasestorage.app',
    measurementId: 'G-EZLLZ8L1N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzVTEjAYktPFN23FYEE_MwHA83MJ0mhas',
    appId: '1:82035476438:android:622d04bb251ee53beec677',
    messagingSenderId: '82035476438',
    projectId: 'leadapp-890b6',
    storageBucket: 'leadapp-890b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjFJnCLECg8ihH8f_Bk_w0aNsz7HUxmN0',
    appId: '1:82035476438:ios:655288f47d89b444eec677',
    messagingSenderId: '82035476438',
    projectId: 'leadapp-890b6',
    storageBucket: 'leadapp-890b6.firebasestorage.app',
    iosBundleId: 'com.mrkvtech.app',
  );
}
